# Generated by Django 5.0.2 on 2024-03-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperature',
            new_name='Measurement',
        ),
    ]
