# Generated by Django 5.0.2 on 2024-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_temperature_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='description',
            field=models.CharField(verbose_name=50),
        ),
    ]
